name: Deploy to Surge

on:
  push:
    branches:
      - tahelbranch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'  

      - name: Install surge
        run: npm install -g surge

      - name: Build the app 
        run: npm install  

      - name: Deploy to Surge
        run: |
          echo "Deploying to Surge.sh..."
          surge --project C:\Users\marco-s\Desktop\tahelfolder\ --domain tahelb.surge.sh



