name: Deploy to Surge

on:
  push:
    branches:
      - tahelbranch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Surge
        run: |
          echo "Deploying to Surge.sh..."
          surge --project C:\Users\marco-s\Desktop\tahelfolder\ --domain tahelbieber.surge.sh

